name: Release Build CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  build:
    env:
      GRPC_BUILD_ENABLE_CCACHE: "ON"
      GH_TOKEN: ${{ secrets.GNUS_TOKEN_1 }}
    runs-on: ${{matrix.host}}
    strategy:
      fail-fast: false
      matrix:
        target: [Android, iOS, OSX, Linux, Windows]
        build-type: [Debug,Release]
        abi: [""]
        include:
          - target: Linux
            host: ubuntu-latest
            abi: x86_64
            build-type: Release
          - target: Linux
            host: ubuntu-latest
            abi: x86_64
            build-type: Debug
          - target: Linux
            host: ubuntu-24.04-arm
            abi: aarch64
            build-type: Release
          - target: Linux
            host: ubuntu-24.04-arm
            abi: aarch64
            build-type: Debug
          - target: Windows
            host: windows-latest
          - target: OSX
            host: macos-latest
          - target: Android
            host: ubuntu-latest
            abi: arm64-v8a
            build-type: Release
          - target: Android
            host: ubuntu-latest
            abi: arm64-v8a
            build-type: Debug
          - target: Android
            host: ubuntu-latest
            abi: armeabi-v7a
            build-type: Release
          - target: Android
            host: ubuntu-latest
            abi: armeabi-v7a
            build-type: Debug
          - target: iOS
            host: macos-latest
        exclude:
          - target: Android
            abi: ""
          - target: Linux
            abi: ""
    steps:
      - name: Configure Linux host
        if: ${{ runner.os == 'Linux'}}
        run: |
          sudo update-alternatives --install /usr/bin/cc cc $(which clang) 100
          sudo update-alternatives --install /usr/bin/c++ c++ $(which clang++) 100
          sudo update-alternatives --set cc $(which clang)
          sudo update-alternatives --set c++ $(which clang++)
           
          sudo apt install ccache ninja-build libvulkan-dev libzstd-dev -y
          echo "CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV

      - name: Configure Windows host
        if: ${{ runner.os == 'Windows'}}
        run: |
          choco install ccache -A

      - name: Configure macOS host
        if: ${{ runner.os == 'macOS'}}
        run: |
          brew install ccache ninja bash gnu-tar
          PATH="$HOMEBREW_PREFIX/opt/gnu-tar/libexec/gnubin:$PATH"
          echo "PATH=$PATH" >> $GITHUB_ENV
          echo "CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV

      - name: Set build directory
        run: |
          if [ '${{matrix.abi}}' ]; then
            BUILD_DIRECTORY=build/${{matrix.target}}/${{matrix.build-type}}/${{matrix.abi}}
          else
            BUILD_DIRECTORY=build/${{matrix.target}}/${{matrix.build-type}}
          fi
          echo "BUILD_DIRECTORY=$BUILD_DIRECTORY" >> $GITHUB_ENV
        shell: bash

      - name: Download thirdparty release
        working-directory: ${{github.workspace}}
        run: |
          if ${{github.event_name == 'pull_request'}}; then
              CURRENT_BRANCH=${{ github.event.pull_request.head.ref }}
          else
              CURRENT_BRANCH=$GITHUB_REF_NAME
          fi

          echo "Identified current branch as ${CURRENT_BRANCH}"

          echo "CURRENT_BRANCH=${CURRENT_BRANCH}" >>$GITHUB_ENV

          if [ "$CURRENT_BRANCH" == "main" ]; then
            thirdparty_branch="main"
          else
            thirdparty_branch="develop"
          fi

          echo "Using ${thirdparty_branch} for thirdparty"

          if [ '${{matrix.abi}}' ]; then
            FILE_NAME=${{matrix.target}}-${{matrix.abi}}-${{matrix.build-type}}.tar.gz
          else
            FILE_NAME=${{matrix.target}}-${{matrix.build-type}}.tar.gz
          fi
          echo "FILE_NAME=${FILE_NAME}" >> $GITHUB_ENV

          mkdir thirdparty
          cd thirdparty

          tag_name="${{matrix.target}}-${thirdparty_branch}-${{matrix.build-type}}"

          gh release download ${tag_name} --repo GeniusVentures/thirdparty -p "${FILE_NAME}"
          tar -zxf "${FILE_NAME}"
        shell: bash

      - name: Download zkLLVM release
        working-directory: ${{github.workspace}}
        run: |
          if [ "$CURRENT_BRANCH" == "main" ]; then
              zkLLVM_branch="main"
          else
              echo "Using develop branch from zkLLVM"
              zkLLVM_branch=develop
          fi

          mkdir zkLLVM
          cd zkLLVM

          if [ '${{matrix.abi}}' ]; then
              tag_name=${{matrix.target}}-${{matrix.abi}}-${zkLLVM_branch}-${{matrix.build-type}}
          else
              tag_name=${{matrix.target}}-${zkLLVM_branch}-${{matrix.build-type}}
          fi

          gh release download ${tag_name} --repo GeniusVentures/zkLLVM -p "*.tar.gz"

          for library in *.tar.gz; do
              tar --exclude='*bin/assigner' --exclude='*bin/clang-zkllvm' --exclude='*bin/llvm-link-zkllvm' --exclude='*bin/transpiler' -xzf "${library}"
          done
        shell: bash

      - name: Download SuperGenius
        run: |
          if [ "$CURRENT_BRANCH" == "main" ]; then
              sgns_branch="main"
          else
              sgns_branch="develop"
          fi

          echo "Using ${sgns_branch} branch from SuperGenius"

          mkdir SuperGenius
          cd SuperGenius

          tag_name="${{matrix.target}}-${sgns_branch}-${{matrix.build-type}}"

          gh release download ${tag_name} --repo GeniusVentures/SuperGenius -p "${FILE_NAME}"

          tar -xzf "${FILE_NAME}"
        shell: bash

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "GeniusSDK"
          submodules: "recursive"

      - name: Configure CMake for Android
        if: ${{ matrix.target == 'Android'}}
        working-directory: ${{github.workspace}}/GeniusSDK
        run: cmake -S build/${{matrix.target}} -B $BUILD_DIRECTORY -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DANDROID_ABI=${{matrix.abi}} -DTHIRDPARTY_BUILD_DIR=${{github.workspace}}/thirdparty/${BUILD_DIRECTORY} -DZKLLVM_DIR=${{github.workspace}}/zkLLVM/${BUILD_DIRECTORY} -DSUPERGENIUS_SRC_DIR=${{github.workspace}}/SuperGenius

      - name: Configure CMake for Mac
        if: ${{ matrix.target == 'OSX'}}
        working-directory: ${{github.workspace}}/GeniusSDK
        run: cmake -S build/${{matrix.target}} -B $BUILD_DIRECTORY -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DPLATFORM=MAC_UNIVERSAL -DTHIRDPARTY_BUILD_DIR=${{github.workspace}}/thirdparty/${BUILD_DIRECTORY} -DZKLLVM_DIR=${{github.workspace}}/zkLLVM/${BUILD_DIRECTORY} -DSUPERGENIUS_SRC_DIR=${{github.workspace}}/SuperGenius

      - name: Configure CMake for iOS
        if: ${{ matrix.target == 'iOS'}}
        working-directory: ${{github.workspace}}/GeniusSDK
        run: cmake -S build/${{matrix.target}} -B $BUILD_DIRECTORY -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DPLATFORM=OS64 -DTHIRDPARTY_BUILD_DIR=${{github.workspace}}/thirdparty/${BUILD_DIRECTORY} -DZKLLVM_DIR=${{github.workspace}}/zkLLVM/${BUILD_DIRECTORY} -DSUPERGENIUS_SRC_DIR=${{github.workspace}}/SuperGenius

      - name: Configure CMake for Linux
        if: ${{matrix.target == 'Linux'}}
        working-directory: ${{github.workspace}}/GeniusSDK
        run: cmake -S build/${{matrix.target}} -B $BUILD_DIRECTORY -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DTHIRDPARTY_BUILD_DIR=${{github.workspace}}/thirdparty/${BUILD_DIRECTORY} -DZKLLVM_DIR=${{github.workspace}}/zkLLVM/${BUILD_DIRECTORY} -DSUPERGENIUS_SRC_DIR=${{github.workspace}}/SuperGenius -DABI_SUBFOLDER_NAME='/${{matrix.abi}}'

      - name: Configure CMake for Windows
        if: ${{matrix.target == 'Windows'}}
        working-directory: ${{github.workspace}}/GeniusSDK
        run: cmake -S build/${{matrix.target}} -B $env:BUILD_DIRECTORY -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DTHIRDPARTY_BUILD_DIR=${{github.workspace}}/thirdparty/$env:BUILD_DIRECTORY -DZKLLVM_DIR=${{github.workspace}}/zkLLVM/$env:BUILD_DIRECTORY -DSUPERGENIUS_SRC_DIR=${{github.workspace}}/SuperGenius

      - name: Build GeniusSDK
        working-directory: ${{github.workspace}}/GeniusSDK/${{env.BUILD_DIRECTORY}}
        run: cmake --build . --config ${{matrix.build-type}} -j
        shell: bash

      - name: Install GeniusSDK
        working-directory: ${{github.workspace}}/GeniusSDK/${{env.BUILD_DIRECTORY}}
        run: cmake --install .

      - name: Compress build artifacts
        working-directory: ${{github.workspace}}/GeniusSDK/${{env.BUILD_DIRECTORY}}
        if: github.ref_name == 'main' || github.ref_name == 'develop'
        run: |
          tar --exclude=.git -czvf ${FILE_NAME} --transform 's|^|${{env.BUILD_DIRECTORY}}/|' GeniusSDK/
        shell: bash

      - name: Release SDK
        working-directory: ${{github.workspace}}/GeniusSDK
        if: github.ref_name == 'main' || github.ref_name == 'develop'
        shell: bash
        run: |
          RELEASE_TAG='${{matrix.target}}-${{github.ref_name}}-${{matrix.build-type}}'

          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV

          if ! gh release view $RELEASE_TAG; then
              echo "Release not found, creating with tag: $RELEASE_TAG"

              if [ '${{ matrix.build-type }}' != 'Release' ]; then
                  RELEASE_TYPE="--prerelease"
              else
                  RELEASE_TYPE="--latest"
              fi

              gh release create $RELEASE_TAG \
                  -n "${CURRENT_BRANCH} branch" \
                  --target "${CURRENT_BRANCH}" \
                  ${RELEASE_TYPE} \
                  -t "${{ matrix.target }} ${CURRENT_BRANCH} branch ${{ matrix.build-type }} build"
          fi

          echo -e "Uploading ${FILE_NAME}"
          gh release upload --clobber ${RELEASE_TAG} "${{env.BUILD_DIRECTORY}}/${FILE_NAME}"
